#!/bin/bash

# Use at least enough arguments to ensure a valid type and action, or error out.
if [ $# -lt 2 ]; then
    echo "not enough arguments: $0 $*" >&2
    exit 1
fi

# Initialize type and action to leave the remaining args as the filelist.
type="$1"
shift
action="$1"
shift

# Use case type to ensure that the taghandler is passed only types it can
# handle.  In this case, use only handle files and error out on anything
# else
case "$type" in
    files)
        # For file type operations, case the possible actions and error
        # for anything unsupported.
        case "$action" in
            update)
                # Iterate the file list because it is not known in advance
                # how many files we will be passed in a given operation.
                for file in $@; do
                   for name in `cat $file`; do
                        cd `dirname $name` 
                        /usr/bin/gacutil -i `basename $name`
                   done
                done
                ;;
            # Use preremove to cleanly stop a service
            # before removing the init file which controls it.
            preremove)
                for file in $@; do
                   for name in `cat $file`; do
                        echo `basename ${name%%.*}` 
                        /usr/bin/gacutil -u `basename ${name%%.*}`
                   done
                done
                ;;
            *)
                echo "ERROR: taghandler $0 invoked for an action ($action) that is not handled" 1>&2
                exit 1
                ;;
        esac
        ;;
    *)
        echo "ERROR: taghandler $0 invoked for a type ($type) that is not handled" 1>&2
        exit 1
        ;;
esac

exit 0
