//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3031.
// 
#pragma warning disable 1591

namespace Nuxleus.Extension.AWS.Sdb {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AmazonSDBBinding", Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")]
    public partial class AmazonSimpleDB : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateDomainOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListDomainsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteDomainOperationCompleted;
        
        private System.Threading.SendOrPostCallback PutAttributesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAttributesOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteAttributesOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AmazonSimpleDB() {
            this.Url = global::Nuxleus.Extension.AWS.Properties.Settings.Default.Nuxleus_Extension_AWS_Sdb_AmazonSimpleDB;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateDomainCompletedEventHandler CreateDomainCompleted;
        
        /// <remarks/>
        public event ListDomainsCompletedEventHandler ListDomainsCompleted;
        
        /// <remarks/>
        public event DeleteDomainCompletedEventHandler DeleteDomainCompleted;
        
        /// <remarks/>
        public event PutAttributesCompletedEventHandler PutAttributesCompleted;
        
        /// <remarks/>
        public event GetAttributesCompletedEventHandler GetAttributesCompleted;
        
        /// <remarks/>
        public event DeleteAttributesCompletedEventHandler DeleteAttributesCompleted;
        
        /// <remarks/>
        public event QueryCompletedEventHandler QueryCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CreateDomain", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("CreateDomainResponse", Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")]
        public CreateDomainResponse CreateDomain([System.Xml.Serialization.XmlElementAttribute("CreateDomain", Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")] CreateDomain CreateDomain1) {
            object[] results = this.Invoke("CreateDomain", new object[] {
                        CreateDomain1});
            return ((CreateDomainResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CreateDomainAsync(CreateDomain CreateDomain1) {
            this.CreateDomainAsync(CreateDomain1, null);
        }
        
        /// <remarks/>
        public void CreateDomainAsync(CreateDomain CreateDomain1, object userState) {
            if ((this.CreateDomainOperationCompleted == null)) {
                this.CreateDomainOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateDomainOperationCompleted);
            }
            this.InvokeAsync("CreateDomain", new object[] {
                        CreateDomain1}, this.CreateDomainOperationCompleted, userState);
        }
        
        private void OnCreateDomainOperationCompleted(object arg) {
            if ((this.CreateDomainCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateDomainCompleted(this, new CreateDomainCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ListDomains", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ListDomainsResponse", Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")]
        public ListDomainsResponse ListDomains([System.Xml.Serialization.XmlElementAttribute("ListDomains", Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")] ListDomains ListDomains1) {
            object[] results = this.Invoke("ListDomains", new object[] {
                        ListDomains1});
            return ((ListDomainsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ListDomainsAsync(ListDomains ListDomains1) {
            this.ListDomainsAsync(ListDomains1, null);
        }
        
        /// <remarks/>
        public void ListDomainsAsync(ListDomains ListDomains1, object userState) {
            if ((this.ListDomainsOperationCompleted == null)) {
                this.ListDomainsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListDomainsOperationCompleted);
            }
            this.InvokeAsync("ListDomains", new object[] {
                        ListDomains1}, this.ListDomainsOperationCompleted, userState);
        }
        
        private void OnListDomainsOperationCompleted(object arg) {
            if ((this.ListDomainsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListDomainsCompleted(this, new ListDomainsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DeleteDomain", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("DeleteDomainResponse", Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")]
        public DeleteDomainResponse DeleteDomain([System.Xml.Serialization.XmlElementAttribute("DeleteDomain", Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")] DeleteDomain DeleteDomain1) {
            object[] results = this.Invoke("DeleteDomain", new object[] {
                        DeleteDomain1});
            return ((DeleteDomainResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteDomainAsync(DeleteDomain DeleteDomain1) {
            this.DeleteDomainAsync(DeleteDomain1, null);
        }
        
        /// <remarks/>
        public void DeleteDomainAsync(DeleteDomain DeleteDomain1, object userState) {
            if ((this.DeleteDomainOperationCompleted == null)) {
                this.DeleteDomainOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteDomainOperationCompleted);
            }
            this.InvokeAsync("DeleteDomain", new object[] {
                        DeleteDomain1}, this.DeleteDomainOperationCompleted, userState);
        }
        
        private void OnDeleteDomainOperationCompleted(object arg) {
            if ((this.DeleteDomainCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteDomainCompleted(this, new DeleteDomainCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("PutAttributes", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("PutAttributesResponse", Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")]
        public PutAttributesResponse PutAttributes([System.Xml.Serialization.XmlElementAttribute("PutAttributes", Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")] PutAttributes PutAttributes1) {
            object[] results = this.Invoke("PutAttributes", new object[] {
                        PutAttributes1});
            return ((PutAttributesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void PutAttributesAsync(PutAttributes PutAttributes1) {
            this.PutAttributesAsync(PutAttributes1, null);
        }
        
        /// <remarks/>
        public void PutAttributesAsync(PutAttributes PutAttributes1, object userState) {
            if ((this.PutAttributesOperationCompleted == null)) {
                this.PutAttributesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPutAttributesOperationCompleted);
            }
            this.InvokeAsync("PutAttributes", new object[] {
                        PutAttributes1}, this.PutAttributesOperationCompleted, userState);
        }
        
        private void OnPutAttributesOperationCompleted(object arg) {
            if ((this.PutAttributesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PutAttributesCompleted(this, new PutAttributesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("GetAttributes", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetAttributesResponse", Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")]
        public GetAttributesResponse GetAttributes([System.Xml.Serialization.XmlElementAttribute("GetAttributes", Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")] GetAttributes GetAttributes1) {
            object[] results = this.Invoke("GetAttributes", new object[] {
                        GetAttributes1});
            return ((GetAttributesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetAttributesAsync(GetAttributes GetAttributes1) {
            this.GetAttributesAsync(GetAttributes1, null);
        }
        
        /// <remarks/>
        public void GetAttributesAsync(GetAttributes GetAttributes1, object userState) {
            if ((this.GetAttributesOperationCompleted == null)) {
                this.GetAttributesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAttributesOperationCompleted);
            }
            this.InvokeAsync("GetAttributes", new object[] {
                        GetAttributes1}, this.GetAttributesOperationCompleted, userState);
        }
        
        private void OnGetAttributesOperationCompleted(object arg) {
            if ((this.GetAttributesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAttributesCompleted(this, new GetAttributesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DeleteAttributes", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("DeleteAttributesResponse", Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")]
        public DeleteAttributesResponse DeleteAttributes([System.Xml.Serialization.XmlElementAttribute("DeleteAttributes", Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")] DeleteAttributes DeleteAttributes1) {
            object[] results = this.Invoke("DeleteAttributes", new object[] {
                        DeleteAttributes1});
            return ((DeleteAttributesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAttributesAsync(DeleteAttributes DeleteAttributes1) {
            this.DeleteAttributesAsync(DeleteAttributes1, null);
        }
        
        /// <remarks/>
        public void DeleteAttributesAsync(DeleteAttributes DeleteAttributes1, object userState) {
            if ((this.DeleteAttributesOperationCompleted == null)) {
                this.DeleteAttributesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteAttributesOperationCompleted);
            }
            this.InvokeAsync("DeleteAttributes", new object[] {
                        DeleteAttributes1}, this.DeleteAttributesOperationCompleted, userState);
        }
        
        private void OnDeleteAttributesOperationCompleted(object arg) {
            if ((this.DeleteAttributesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteAttributesCompleted(this, new DeleteAttributesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Query", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("QueryResponse", Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")]
        public QueryResponse Query([System.Xml.Serialization.XmlElementAttribute("Query", Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")] Query Query1) {
            object[] results = this.Invoke("Query", new object[] {
                        Query1});
            return ((QueryResponse)(results[0]));
        }
        
        /// <remarks/>
        public void QueryAsync(Query Query1) {
            this.QueryAsync(Query1, null);
        }
        
        /// <remarks/>
        public void QueryAsync(Query Query1, object userState) {
            if ((this.QueryOperationCompleted == null)) {
                this.QueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryOperationCompleted);
            }
            this.InvokeAsync("Query", new object[] {
                        Query1}, this.QueryOperationCompleted, userState);
        }
        
        private void OnQueryOperationCompleted(object arg) {
            if ((this.QueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryCompleted(this, new QueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")]
    public partial class CreateDomain {
        
        private string domainNameField;
        
        /// <remarks/>
        public string DomainName {
            get {
                return this.domainNameField;
            }
            set {
                this.domainNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")]
    public partial class Attribute {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")]
    public partial class ReplaceableAttribute {
        
        private string nameField;
        
        private string valueField;
        
        private bool replaceField;
        
        private bool replaceFieldSpecified;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public bool Replace {
            get {
                return this.replaceField;
            }
            set {
                this.replaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReplaceSpecified {
            get {
                return this.replaceFieldSpecified;
            }
            set {
                this.replaceFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")]
    public partial class CreateDomainResponse {
        
        private ResponseMetadata responseMetadataField;
        
        /// <remarks/>
        public ResponseMetadata ResponseMetadata {
            get {
                return this.responseMetadataField;
            }
            set {
                this.responseMetadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")]
    public partial class ResponseMetadata {
        
        private string requestIdField;
        
        private string boxUsageField;
        
        /// <remarks/>
        public string RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        public string BoxUsage {
            get {
                return this.boxUsageField;
            }
            set {
                this.boxUsageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")]
    public partial class ListDomains {
        
        private int maxNumberOfDomainsField;
        
        private bool maxNumberOfDomainsFieldSpecified;
        
        private string nextTokenField;
        
        /// <remarks/>
        public int MaxNumberOfDomains {
            get {
                return this.maxNumberOfDomainsField;
            }
            set {
                this.maxNumberOfDomainsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxNumberOfDomainsSpecified {
            get {
                return this.maxNumberOfDomainsFieldSpecified;
            }
            set {
                this.maxNumberOfDomainsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string NextToken {
            get {
                return this.nextTokenField;
            }
            set {
                this.nextTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")]
    public partial class ListDomainsResponse {
        
        private ListDomainsResult listDomainsResultField;
        
        private ResponseMetadata responseMetadataField;
        
        /// <remarks/>
        public ListDomainsResult ListDomainsResult {
            get {
                return this.listDomainsResultField;
            }
            set {
                this.listDomainsResultField = value;
            }
        }
        
        /// <remarks/>
        public ResponseMetadata ResponseMetadata {
            get {
                return this.responseMetadataField;
            }
            set {
                this.responseMetadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")]
    public partial class ListDomainsResult {
        
        private string[] domainNameField;
        
        private string nextTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DomainName")]
        public string[] DomainName {
            get {
                return this.domainNameField;
            }
            set {
                this.domainNameField = value;
            }
        }
        
        /// <remarks/>
        public string NextToken {
            get {
                return this.nextTokenField;
            }
            set {
                this.nextTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")]
    public partial class DeleteDomain {
        
        private string domainNameField;
        
        /// <remarks/>
        public string DomainName {
            get {
                return this.domainNameField;
            }
            set {
                this.domainNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")]
    public partial class DeleteDomainResponse {
        
        private ResponseMetadata responseMetadataField;
        
        /// <remarks/>
        public ResponseMetadata ResponseMetadata {
            get {
                return this.responseMetadataField;
            }
            set {
                this.responseMetadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")]
    public partial class PutAttributes {
        
        private string domainNameField;
        
        private string itemNameField;
        
        private ReplaceableAttribute[] attributeField;
        
        /// <remarks/>
        public string DomainName {
            get {
                return this.domainNameField;
            }
            set {
                this.domainNameField = value;
            }
        }
        
        /// <remarks/>
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attribute")]
        public ReplaceableAttribute[] Attribute {
            get {
                return this.attributeField;
            }
            set {
                this.attributeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")]
    public partial class PutAttributesResponse {
        
        private ResponseMetadata responseMetadataField;
        
        /// <remarks/>
        public ResponseMetadata ResponseMetadata {
            get {
                return this.responseMetadataField;
            }
            set {
                this.responseMetadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")]
    public partial class GetAttributes {
        
        private string domainNameField;
        
        private string itemNameField;
        
        private string[] attributeNameField;
        
        /// <remarks/>
        public string DomainName {
            get {
                return this.domainNameField;
            }
            set {
                this.domainNameField = value;
            }
        }
        
        /// <remarks/>
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttributeName")]
        public string[] AttributeName {
            get {
                return this.attributeNameField;
            }
            set {
                this.attributeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")]
    public partial class GetAttributesResponse {
        
        private Attribute[] getAttributesResultField;
        
        private ResponseMetadata responseMetadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Attribute[] GetAttributesResult {
            get {
                return this.getAttributesResultField;
            }
            set {
                this.getAttributesResultField = value;
            }
        }
        
        /// <remarks/>
        public ResponseMetadata ResponseMetadata {
            get {
                return this.responseMetadataField;
            }
            set {
                this.responseMetadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")]
    public partial class DeleteAttributes {
        
        private string domainNameField;
        
        private string itemNameField;
        
        private Attribute[] attributeField;
        
        /// <remarks/>
        public string DomainName {
            get {
                return this.domainNameField;
            }
            set {
                this.domainNameField = value;
            }
        }
        
        /// <remarks/>
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attribute")]
        public Attribute[] Attribute {
            get {
                return this.attributeField;
            }
            set {
                this.attributeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")]
    public partial class DeleteAttributesResponse {
        
        private ResponseMetadata responseMetadataField;
        
        /// <remarks/>
        public ResponseMetadata ResponseMetadata {
            get {
                return this.responseMetadataField;
            }
            set {
                this.responseMetadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")]
    public partial class Query {
        
        private string domainNameField;
        
        private string queryExpressionField;
        
        private int maxNumberOfItemsField;
        
        private bool maxNumberOfItemsFieldSpecified;
        
        private string nextTokenField;
        
        /// <remarks/>
        public string DomainName {
            get {
                return this.domainNameField;
            }
            set {
                this.domainNameField = value;
            }
        }
        
        /// <remarks/>
        public string QueryExpression {
            get {
                return this.queryExpressionField;
            }
            set {
                this.queryExpressionField = value;
            }
        }
        
        /// <remarks/>
        public int MaxNumberOfItems {
            get {
                return this.maxNumberOfItemsField;
            }
            set {
                this.maxNumberOfItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxNumberOfItemsSpecified {
            get {
                return this.maxNumberOfItemsFieldSpecified;
            }
            set {
                this.maxNumberOfItemsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string NextToken {
            get {
                return this.nextTokenField;
            }
            set {
                this.nextTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")]
    public partial class QueryResponse {
        
        private QueryResult queryResultField;
        
        private ResponseMetadata responseMetadataField;
        
        /// <remarks/>
        public QueryResult QueryResult {
            get {
                return this.queryResultField;
            }
            set {
                this.queryResultField = value;
            }
        }
        
        /// <remarks/>
        public ResponseMetadata ResponseMetadata {
            get {
                return this.responseMetadataField;
            }
            set {
                this.responseMetadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2007-11-07/")]
    public partial class QueryResult {
        
        private string[] itemNameField;
        
        private string nextTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemName")]
        public string[] ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        public string NextToken {
            get {
                return this.nextTokenField;
            }
            set {
                this.nextTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    public delegate void CreateDomainCompletedEventHandler(object sender, CreateDomainCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateDomainCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateDomainCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreateDomainResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreateDomainResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    public delegate void ListDomainsCompletedEventHandler(object sender, ListDomainsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListDomainsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListDomainsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListDomainsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListDomainsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    public delegate void DeleteDomainCompletedEventHandler(object sender, DeleteDomainCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteDomainCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteDomainCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeleteDomainResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeleteDomainResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    public delegate void PutAttributesCompletedEventHandler(object sender, PutAttributesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PutAttributesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PutAttributesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PutAttributesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PutAttributesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    public delegate void GetAttributesCompletedEventHandler(object sender, GetAttributesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAttributesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAttributesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetAttributesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetAttributesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    public delegate void DeleteAttributesCompletedEventHandler(object sender, DeleteAttributesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteAttributesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteAttributesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeleteAttributesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeleteAttributesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    public delegate void QueryCompletedEventHandler(object sender, QueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QueryResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QueryResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591