//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3031.
// 
#pragma warning disable 1591

namespace Nuxleus.Extension.AWS.Sqs {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="QueueServiceBinding", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
    public partial class QueueServiceBinding : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateQueueOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListQueuesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public QueueServiceBinding() {
            this.Url = global::Nuxleus.Extension.AWS.Properties.Settings.Default.Nuxleus_Extension_AWS_Sqs_QueueService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateQueueCompletedEventHandler CreateQueueCompleted;
        
        /// <remarks/>
        public event ListQueuesCompletedEventHandler ListQueuesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CreateQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("CreateQueueResponse", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
        public CreateQueueResponse CreateQueue([System.Xml.Serialization.XmlElementAttribute("CreateQueue", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")] CreateQueue CreateQueue1) {
            object[] results = this.Invoke("CreateQueue", new object[] {
                        CreateQueue1});
            return ((CreateQueueResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CreateQueueAsync(CreateQueue CreateQueue1) {
            this.CreateQueueAsync(CreateQueue1, null);
        }
        
        /// <remarks/>
        public void CreateQueueAsync(CreateQueue CreateQueue1, object userState) {
            if ((this.CreateQueueOperationCompleted == null)) {
                this.CreateQueueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateQueueOperationCompleted);
            }
            this.InvokeAsync("CreateQueue", new object[] {
                        CreateQueue1}, this.CreateQueueOperationCompleted, userState);
        }
        
        private void OnCreateQueueOperationCompleted(object arg) {
            if ((this.CreateQueueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateQueueCompleted(this, new CreateQueueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ListQueues", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ListQueuesResponse", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
        public ListQueuesResponse ListQueues([System.Xml.Serialization.XmlElementAttribute("ListQueues", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")] ListQueues ListQueues1) {
            object[] results = this.Invoke("ListQueues", new object[] {
                        ListQueues1});
            return ((ListQueuesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ListQueuesAsync(ListQueues ListQueues1) {
            this.ListQueuesAsync(ListQueues1, null);
        }
        
        /// <remarks/>
        public void ListQueuesAsync(ListQueues ListQueues1, object userState) {
            if ((this.ListQueuesOperationCompleted == null)) {
                this.ListQueuesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListQueuesOperationCompleted);
            }
            this.InvokeAsync("ListQueues", new object[] {
                        ListQueues1}, this.ListQueuesOperationCompleted, userState);
        }
        
        private void OnListQueuesOperationCompleted(object arg) {
            if ((this.ListQueuesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListQueuesCompleted(this, new ListQueuesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="QueueServiceHttpsBinding", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
    public partial class QueueServiceHttpsBinding : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateQueueOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListQueuesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public QueueServiceHttpsBinding() {
            this.Url = "https://queue.amazonaws.com";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateQueueCompletedEventHandler CreateQueueCompleted;
        
        /// <remarks/>
        public event ListQueuesCompletedEventHandler ListQueuesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CreateQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("CreateQueueResponse", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
        public CreateQueueResponse CreateQueue([System.Xml.Serialization.XmlElementAttribute("CreateQueue", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")] CreateQueue CreateQueue1) {
            object[] results = this.Invoke("CreateQueue", new object[] {
                        CreateQueue1});
            return ((CreateQueueResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CreateQueueAsync(CreateQueue CreateQueue1) {
            this.CreateQueueAsync(CreateQueue1, null);
        }
        
        /// <remarks/>
        public void CreateQueueAsync(CreateQueue CreateQueue1, object userState) {
            if ((this.CreateQueueOperationCompleted == null)) {
                this.CreateQueueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateQueueOperationCompleted);
            }
            this.InvokeAsync("CreateQueue", new object[] {
                        CreateQueue1}, this.CreateQueueOperationCompleted, userState);
        }
        
        private void OnCreateQueueOperationCompleted(object arg) {
            if ((this.CreateQueueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateQueueCompleted(this, new CreateQueueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ListQueues", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ListQueuesResponse", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
        public ListQueuesResponse ListQueues([System.Xml.Serialization.XmlElementAttribute("ListQueues", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")] ListQueues ListQueues1) {
            object[] results = this.Invoke("ListQueues", new object[] {
                        ListQueues1});
            return ((ListQueuesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ListQueuesAsync(ListQueues ListQueues1) {
            this.ListQueuesAsync(ListQueues1, null);
        }
        
        /// <remarks/>
        public void ListQueuesAsync(ListQueues ListQueues1, object userState) {
            if ((this.ListQueuesOperationCompleted == null)) {
                this.ListQueuesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListQueuesOperationCompleted);
            }
            this.InvokeAsync("ListQueues", new object[] {
                        ListQueues1}, this.ListQueuesOperationCompleted, userState);
        }
        
        private void OnListQueuesOperationCompleted(object arg) {
            if ((this.ListQueuesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListQueuesCompleted(this, new ListQueuesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MessageQueueBinding", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
    public partial class MessageQueueBinding : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DeleteMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteQueueOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetQueueAttributesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReceiveMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetQueueAttributesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MessageQueueBinding() {
            this.Url = global::Nuxleus.Extension.AWS.Properties.Settings.Default.Nuxleus_Extension_AWS_Sqs_QueueService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DeleteMessageCompletedEventHandler DeleteMessageCompleted;
        
        /// <remarks/>
        public event DeleteQueueCompletedEventHandler DeleteQueueCompleted;
        
        /// <remarks/>
        public event GetQueueAttributesCompletedEventHandler GetQueueAttributesCompleted;
        
        /// <remarks/>
        public event ReceiveMessageCompletedEventHandler ReceiveMessageCompleted;
        
        /// <remarks/>
        public event SendMessageCompletedEventHandler SendMessageCompleted;
        
        /// <remarks/>
        public event SetQueueAttributesCompletedEventHandler SetQueueAttributesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DeleteMessage", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("DeleteMessageResponse", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
        public DeleteMessageResponse DeleteMessage([System.Xml.Serialization.XmlElementAttribute("DeleteMessage", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")] DeleteMessage DeleteMessage1) {
            object[] results = this.Invoke("DeleteMessage", new object[] {
                        DeleteMessage1});
            return ((DeleteMessageResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteMessageAsync(DeleteMessage DeleteMessage1) {
            this.DeleteMessageAsync(DeleteMessage1, null);
        }
        
        /// <remarks/>
        public void DeleteMessageAsync(DeleteMessage DeleteMessage1, object userState) {
            if ((this.DeleteMessageOperationCompleted == null)) {
                this.DeleteMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteMessageOperationCompleted);
            }
            this.InvokeAsync("DeleteMessage", new object[] {
                        DeleteMessage1}, this.DeleteMessageOperationCompleted, userState);
        }
        
        private void OnDeleteMessageOperationCompleted(object arg) {
            if ((this.DeleteMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteMessageCompleted(this, new DeleteMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DeleteQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("DeleteQueueResponse", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
        public DeleteQueueResponse DeleteQueue([System.Xml.Serialization.XmlElementAttribute("DeleteQueue", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")] DeleteQueue DeleteQueue1) {
            object[] results = this.Invoke("DeleteQueue", new object[] {
                        DeleteQueue1});
            return ((DeleteQueueResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteQueueAsync(DeleteQueue DeleteQueue1) {
            this.DeleteQueueAsync(DeleteQueue1, null);
        }
        
        /// <remarks/>
        public void DeleteQueueAsync(DeleteQueue DeleteQueue1, object userState) {
            if ((this.DeleteQueueOperationCompleted == null)) {
                this.DeleteQueueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteQueueOperationCompleted);
            }
            this.InvokeAsync("DeleteQueue", new object[] {
                        DeleteQueue1}, this.DeleteQueueOperationCompleted, userState);
        }
        
        private void OnDeleteQueueOperationCompleted(object arg) {
            if ((this.DeleteQueueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteQueueCompleted(this, new DeleteQueueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("GetQueueAttributes", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetQueueAttributesResponse", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
        public GetQueueAttributesResponse GetQueueAttributes([System.Xml.Serialization.XmlElementAttribute("GetQueueAttributes", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")] GetQueueAttributes GetQueueAttributes1) {
            object[] results = this.Invoke("GetQueueAttributes", new object[] {
                        GetQueueAttributes1});
            return ((GetQueueAttributesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetQueueAttributesAsync(GetQueueAttributes GetQueueAttributes1) {
            this.GetQueueAttributesAsync(GetQueueAttributes1, null);
        }
        
        /// <remarks/>
        public void GetQueueAttributesAsync(GetQueueAttributes GetQueueAttributes1, object userState) {
            if ((this.GetQueueAttributesOperationCompleted == null)) {
                this.GetQueueAttributesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetQueueAttributesOperationCompleted);
            }
            this.InvokeAsync("GetQueueAttributes", new object[] {
                        GetQueueAttributes1}, this.GetQueueAttributesOperationCompleted, userState);
        }
        
        private void OnGetQueueAttributesOperationCompleted(object arg) {
            if ((this.GetQueueAttributesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetQueueAttributesCompleted(this, new GetQueueAttributesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ReceiveMessage", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ReceiveMessageResponse", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
        public ReceiveMessageResponse ReceiveMessage([System.Xml.Serialization.XmlElementAttribute("ReceiveMessage", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")] ReceiveMessage ReceiveMessage1) {
            object[] results = this.Invoke("ReceiveMessage", new object[] {
                        ReceiveMessage1});
            return ((ReceiveMessageResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ReceiveMessageAsync(ReceiveMessage ReceiveMessage1) {
            this.ReceiveMessageAsync(ReceiveMessage1, null);
        }
        
        /// <remarks/>
        public void ReceiveMessageAsync(ReceiveMessage ReceiveMessage1, object userState) {
            if ((this.ReceiveMessageOperationCompleted == null)) {
                this.ReceiveMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReceiveMessageOperationCompleted);
            }
            this.InvokeAsync("ReceiveMessage", new object[] {
                        ReceiveMessage1}, this.ReceiveMessageOperationCompleted, userState);
        }
        
        private void OnReceiveMessageOperationCompleted(object arg) {
            if ((this.ReceiveMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReceiveMessageCompleted(this, new ReceiveMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SendMessage", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("SendMessageResponse", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
        public SendMessageResponse SendMessage([System.Xml.Serialization.XmlElementAttribute("SendMessage", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")] SendMessage SendMessage1) {
            object[] results = this.Invoke("SendMessage", new object[] {
                        SendMessage1});
            return ((SendMessageResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SendMessageAsync(SendMessage SendMessage1) {
            this.SendMessageAsync(SendMessage1, null);
        }
        
        /// <remarks/>
        public void SendMessageAsync(SendMessage SendMessage1, object userState) {
            if ((this.SendMessageOperationCompleted == null)) {
                this.SendMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMessageOperationCompleted);
            }
            this.InvokeAsync("SendMessage", new object[] {
                        SendMessage1}, this.SendMessageOperationCompleted, userState);
        }
        
        private void OnSendMessageOperationCompleted(object arg) {
            if ((this.SendMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMessageCompleted(this, new SendMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SetQueueAttributes", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("SetQueueAttributesResponse", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
        public SetQueueAttributesResponse SetQueueAttributes([System.Xml.Serialization.XmlArrayAttribute("SetQueueAttributes", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")] [System.Xml.Serialization.XmlArrayItemAttribute("Attribute", IsNullable=false)] Attribute[] SetQueueAttributes1) {
            object[] results = this.Invoke("SetQueueAttributes", new object[] {
                        SetQueueAttributes1});
            return ((SetQueueAttributesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SetQueueAttributesAsync(Attribute[] SetQueueAttributes1) {
            this.SetQueueAttributesAsync(SetQueueAttributes1, null);
        }
        
        /// <remarks/>
        public void SetQueueAttributesAsync(Attribute[] SetQueueAttributes1, object userState) {
            if ((this.SetQueueAttributesOperationCompleted == null)) {
                this.SetQueueAttributesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetQueueAttributesOperationCompleted);
            }
            this.InvokeAsync("SetQueueAttributes", new object[] {
                        SetQueueAttributes1}, this.SetQueueAttributesOperationCompleted, userState);
        }
        
        private void OnSetQueueAttributesOperationCompleted(object arg) {
            if ((this.SetQueueAttributesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetQueueAttributesCompleted(this, new SetQueueAttributesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MessageQueueHttpsBinding", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
    public partial class MessageQueueHttpsBinding : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DeleteMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteQueueOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetQueueAttributesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReceiveMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetQueueAttributesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MessageQueueHttpsBinding() {
            this.Url = "https://queue.amazonaws.com";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DeleteMessageCompletedEventHandler DeleteMessageCompleted;
        
        /// <remarks/>
        public event DeleteQueueCompletedEventHandler DeleteQueueCompleted;
        
        /// <remarks/>
        public event GetQueueAttributesCompletedEventHandler GetQueueAttributesCompleted;
        
        /// <remarks/>
        public event ReceiveMessageCompletedEventHandler ReceiveMessageCompleted;
        
        /// <remarks/>
        public event SendMessageCompletedEventHandler SendMessageCompleted;
        
        /// <remarks/>
        public event SetQueueAttributesCompletedEventHandler SetQueueAttributesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DeleteMessage", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("DeleteMessageResponse", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
        public DeleteMessageResponse DeleteMessage([System.Xml.Serialization.XmlElementAttribute("DeleteMessage", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")] DeleteMessage DeleteMessage1) {
            object[] results = this.Invoke("DeleteMessage", new object[] {
                        DeleteMessage1});
            return ((DeleteMessageResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteMessageAsync(DeleteMessage DeleteMessage1) {
            this.DeleteMessageAsync(DeleteMessage1, null);
        }
        
        /// <remarks/>
        public void DeleteMessageAsync(DeleteMessage DeleteMessage1, object userState) {
            if ((this.DeleteMessageOperationCompleted == null)) {
                this.DeleteMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteMessageOperationCompleted);
            }
            this.InvokeAsync("DeleteMessage", new object[] {
                        DeleteMessage1}, this.DeleteMessageOperationCompleted, userState);
        }
        
        private void OnDeleteMessageOperationCompleted(object arg) {
            if ((this.DeleteMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteMessageCompleted(this, new DeleteMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DeleteQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("DeleteQueueResponse", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
        public DeleteQueueResponse DeleteQueue([System.Xml.Serialization.XmlElementAttribute("DeleteQueue", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")] DeleteQueue DeleteQueue1) {
            object[] results = this.Invoke("DeleteQueue", new object[] {
                        DeleteQueue1});
            return ((DeleteQueueResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteQueueAsync(DeleteQueue DeleteQueue1) {
            this.DeleteQueueAsync(DeleteQueue1, null);
        }
        
        /// <remarks/>
        public void DeleteQueueAsync(DeleteQueue DeleteQueue1, object userState) {
            if ((this.DeleteQueueOperationCompleted == null)) {
                this.DeleteQueueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteQueueOperationCompleted);
            }
            this.InvokeAsync("DeleteQueue", new object[] {
                        DeleteQueue1}, this.DeleteQueueOperationCompleted, userState);
        }
        
        private void OnDeleteQueueOperationCompleted(object arg) {
            if ((this.DeleteQueueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteQueueCompleted(this, new DeleteQueueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("GetQueueAttributes", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetQueueAttributesResponse", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
        public GetQueueAttributesResponse GetQueueAttributes([System.Xml.Serialization.XmlElementAttribute("GetQueueAttributes", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")] GetQueueAttributes GetQueueAttributes1) {
            object[] results = this.Invoke("GetQueueAttributes", new object[] {
                        GetQueueAttributes1});
            return ((GetQueueAttributesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetQueueAttributesAsync(GetQueueAttributes GetQueueAttributes1) {
            this.GetQueueAttributesAsync(GetQueueAttributes1, null);
        }
        
        /// <remarks/>
        public void GetQueueAttributesAsync(GetQueueAttributes GetQueueAttributes1, object userState) {
            if ((this.GetQueueAttributesOperationCompleted == null)) {
                this.GetQueueAttributesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetQueueAttributesOperationCompleted);
            }
            this.InvokeAsync("GetQueueAttributes", new object[] {
                        GetQueueAttributes1}, this.GetQueueAttributesOperationCompleted, userState);
        }
        
        private void OnGetQueueAttributesOperationCompleted(object arg) {
            if ((this.GetQueueAttributesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetQueueAttributesCompleted(this, new GetQueueAttributesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ReceiveMessage", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ReceiveMessageResponse", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
        public ReceiveMessageResponse ReceiveMessage([System.Xml.Serialization.XmlElementAttribute("ReceiveMessage", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")] ReceiveMessage ReceiveMessage1) {
            object[] results = this.Invoke("ReceiveMessage", new object[] {
                        ReceiveMessage1});
            return ((ReceiveMessageResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ReceiveMessageAsync(ReceiveMessage ReceiveMessage1) {
            this.ReceiveMessageAsync(ReceiveMessage1, null);
        }
        
        /// <remarks/>
        public void ReceiveMessageAsync(ReceiveMessage ReceiveMessage1, object userState) {
            if ((this.ReceiveMessageOperationCompleted == null)) {
                this.ReceiveMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReceiveMessageOperationCompleted);
            }
            this.InvokeAsync("ReceiveMessage", new object[] {
                        ReceiveMessage1}, this.ReceiveMessageOperationCompleted, userState);
        }
        
        private void OnReceiveMessageOperationCompleted(object arg) {
            if ((this.ReceiveMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReceiveMessageCompleted(this, new ReceiveMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SendMessage", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("SendMessageResponse", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
        public SendMessageResponse SendMessage([System.Xml.Serialization.XmlElementAttribute("SendMessage", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")] SendMessage SendMessage1) {
            object[] results = this.Invoke("SendMessage", new object[] {
                        SendMessage1});
            return ((SendMessageResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SendMessageAsync(SendMessage SendMessage1) {
            this.SendMessageAsync(SendMessage1, null);
        }
        
        /// <remarks/>
        public void SendMessageAsync(SendMessage SendMessage1, object userState) {
            if ((this.SendMessageOperationCompleted == null)) {
                this.SendMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMessageOperationCompleted);
            }
            this.InvokeAsync("SendMessage", new object[] {
                        SendMessage1}, this.SendMessageOperationCompleted, userState);
        }
        
        private void OnSendMessageOperationCompleted(object arg) {
            if ((this.SendMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMessageCompleted(this, new SendMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SetQueueAttributes", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("SetQueueAttributesResponse", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
        public SetQueueAttributesResponse SetQueueAttributes([System.Xml.Serialization.XmlArrayAttribute("SetQueueAttributes", Namespace="http://queue.amazonaws.com/doc/2008-01-01/")] [System.Xml.Serialization.XmlArrayItemAttribute("Attribute", IsNullable=false)] Attribute[] SetQueueAttributes1) {
            object[] results = this.Invoke("SetQueueAttributes", new object[] {
                        SetQueueAttributes1});
            return ((SetQueueAttributesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SetQueueAttributesAsync(Attribute[] SetQueueAttributes1) {
            this.SetQueueAttributesAsync(SetQueueAttributes1, null);
        }
        
        /// <remarks/>
        public void SetQueueAttributesAsync(Attribute[] SetQueueAttributes1, object userState) {
            if ((this.SetQueueAttributesOperationCompleted == null)) {
                this.SetQueueAttributesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetQueueAttributesOperationCompleted);
            }
            this.InvokeAsync("SetQueueAttributes", new object[] {
                        SetQueueAttributes1}, this.SetQueueAttributesOperationCompleted, userState);
        }
        
        private void OnSetQueueAttributesOperationCompleted(object arg) {
            if ((this.SetQueueAttributesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetQueueAttributesCompleted(this, new SetQueueAttributesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
    public partial class CreateQueue {
        
        private string queueNameField;
        
        private string defaultVisibilityTimeoutField;
        
        /// <remarks/>
        public string QueueName {
            get {
                return this.queueNameField;
            }
            set {
                this.queueNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string DefaultVisibilityTimeout {
            get {
                return this.defaultVisibilityTimeoutField;
            }
            set {
                this.defaultVisibilityTimeoutField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
    public partial class CreateQueueResponse {
        
        private CreateQueueResult createQueueResultField;
        
        private ResponseMetadata responseMetadataField;
        
        /// <remarks/>
        public CreateQueueResult CreateQueueResult {
            get {
                return this.createQueueResultField;
            }
            set {
                this.createQueueResultField = value;
            }
        }
        
        /// <remarks/>
        public ResponseMetadata ResponseMetadata {
            get {
                return this.responseMetadataField;
            }
            set {
                this.responseMetadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
    public partial class CreateQueueResult {
        
        private string queueUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string QueueUrl {
            get {
                return this.queueUrlField;
            }
            set {
                this.queueUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
    public partial class ResponseMetadata {
        
        private string requestIdField;
        
        /// <remarks/>
        public string RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
    public partial class ListQueues {
        
        private string queueNamePrefixField;
        
        /// <remarks/>
        public string QueueNamePrefix {
            get {
                return this.queueNamePrefixField;
            }
            set {
                this.queueNamePrefixField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
    public partial class ListQueuesResponse {
        
        private string[] listQueuesResultField;
        
        private ResponseMetadata responseMetadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("QueueUrl", DataType="anyURI", IsNullable=false)]
        public string[] ListQueuesResult {
            get {
                return this.listQueuesResultField;
            }
            set {
                this.listQueuesResultField = value;
            }
        }
        
        /// <remarks/>
        public ResponseMetadata ResponseMetadata {
            get {
                return this.responseMetadataField;
            }
            set {
                this.responseMetadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
    public partial class DeleteMessage {
        
        private string receiptHandleField;
        
        /// <remarks/>
        public string ReceiptHandle {
            get {
                return this.receiptHandleField;
            }
            set {
                this.receiptHandleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
    public partial class DeleteMessageResponse {
        
        private ResponseMetadata responseMetadataField;
        
        /// <remarks/>
        public ResponseMetadata ResponseMetadata {
            get {
                return this.responseMetadataField;
            }
            set {
                this.responseMetadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
    public partial class DeleteQueue {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
    public partial class DeleteQueueResponse {
        
        private ResponseMetadata responseMetadataField;
        
        /// <remarks/>
        public ResponseMetadata ResponseMetadata {
            get {
                return this.responseMetadataField;
            }
            set {
                this.responseMetadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
    public partial class GetQueueAttributes {
        
        private string[] attributeNameField;
        
        private string unusedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttributeName")]
        public string[] AttributeName {
            get {
                return this.attributeNameField;
            }
            set {
                this.attributeNameField = value;
            }
        }
        
        /// <remarks/>
        public string Unused {
            get {
                return this.unusedField;
            }
            set {
                this.unusedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
    public partial class GetQueueAttributesResponse {
        
        private Attribute[] getQueueAttributesResultField;
        
        private ResponseMetadata responseMetadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Attribute", IsNullable=false)]
        public Attribute[] GetQueueAttributesResult {
            get {
                return this.getQueueAttributesResultField;
            }
            set {
                this.getQueueAttributesResultField = value;
            }
        }
        
        /// <remarks/>
        public ResponseMetadata ResponseMetadata {
            get {
                return this.responseMetadataField;
            }
            set {
                this.responseMetadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
    public partial class Attribute {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
    public partial class ReceiveMessage {
        
        private string maxNumberOfMessagesField;
        
        private string visibilityTimeoutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string MaxNumberOfMessages {
            get {
                return this.maxNumberOfMessagesField;
            }
            set {
                this.maxNumberOfMessagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string VisibilityTimeout {
            get {
                return this.visibilityTimeoutField;
            }
            set {
                this.visibilityTimeoutField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
    public partial class ReceiveMessageResponse {
        
        private Message[] receiveMessageResultField;
        
        private ResponseMetadata responseMetadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Message", IsNullable=false)]
        public Message[] ReceiveMessageResult {
            get {
                return this.receiveMessageResultField;
            }
            set {
                this.receiveMessageResultField = value;
            }
        }
        
        /// <remarks/>
        public ResponseMetadata ResponseMetadata {
            get {
                return this.responseMetadataField;
            }
            set {
                this.responseMetadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
    public partial class Message {
        
        private string messageIdField;
        
        private string receiptHandleField;
        
        private string mD5OfBodyField;
        
        private string bodyField;
        
        /// <remarks/>
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiptHandle {
            get {
                return this.receiptHandleField;
            }
            set {
                this.receiptHandleField = value;
            }
        }
        
        /// <remarks/>
        public string MD5OfBody {
            get {
                return this.mD5OfBodyField;
            }
            set {
                this.mD5OfBodyField = value;
            }
        }
        
        /// <remarks/>
        public string Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
    public partial class SendMessage {
        
        private string messageBodyField;
        
        /// <remarks/>
        public string MessageBody {
            get {
                return this.messageBodyField;
            }
            set {
                this.messageBodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
    public partial class SendMessageResponse {
        
        private SendMessageResult sendMessageResultField;
        
        private ResponseMetadata responseMetadataField;
        
        /// <remarks/>
        public SendMessageResult SendMessageResult {
            get {
                return this.sendMessageResultField;
            }
            set {
                this.sendMessageResultField = value;
            }
        }
        
        /// <remarks/>
        public ResponseMetadata ResponseMetadata {
            get {
                return this.responseMetadataField;
            }
            set {
                this.responseMetadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
    public partial class SendMessageResult {
        
        private string messageIdField;
        
        private string mD5OfMessageBodyField;
        
        /// <remarks/>
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        public string MD5OfMessageBody {
            get {
                return this.mD5OfMessageBodyField;
            }
            set {
                this.mD5OfMessageBodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3031")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://queue.amazonaws.com/doc/2008-01-01/")]
    public partial class SetQueueAttributesResponse {
        
        private ResponseMetadata responseMetadataField;
        
        /// <remarks/>
        public ResponseMetadata ResponseMetadata {
            get {
                return this.responseMetadataField;
            }
            set {
                this.responseMetadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    public delegate void CreateQueueCompletedEventHandler(object sender, CreateQueueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateQueueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateQueueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreateQueueResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreateQueueResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    public delegate void ListQueuesCompletedEventHandler(object sender, ListQueuesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListQueuesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListQueuesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListQueuesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListQueuesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    public delegate void DeleteMessageCompletedEventHandler(object sender, DeleteMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeleteMessageResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeleteMessageResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    public delegate void DeleteQueueCompletedEventHandler(object sender, DeleteQueueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteQueueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteQueueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeleteQueueResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeleteQueueResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    public delegate void GetQueueAttributesCompletedEventHandler(object sender, GetQueueAttributesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetQueueAttributesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetQueueAttributesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetQueueAttributesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetQueueAttributesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    public delegate void ReceiveMessageCompletedEventHandler(object sender, ReceiveMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReceiveMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReceiveMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReceiveMessageResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReceiveMessageResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    public delegate void SendMessageCompletedEventHandler(object sender, SendMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendMessageResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendMessageResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    public delegate void SetQueueAttributesCompletedEventHandler(object sender, SetQueueAttributesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3031")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetQueueAttributesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetQueueAttributesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SetQueueAttributesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SetQueueAttributesResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591