//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1318
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1318.
// 
#pragma warning disable 1591

namespace Nuxleus.Amp.Fm {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1318")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SearchSoap", Namespace="http://amp.fm/service")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ValueType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class Search : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SearchTitleOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchArtistOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchGenreOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchLyricsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Search() {
            this.Url = global::Nuxleus.Properties.Settings.Default.nux_Nuxleus_Amp_Fm_Search;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SearchTitleCompletedEventHandler SearchTitleCompleted;
        
        /// <remarks/>
        public event SearchArtistCompletedEventHandler SearchArtistCompleted;
        
        /// <remarks/>
        public event SearchGenreCompletedEventHandler SearchGenreCompleted;
        
        /// <remarks/>
        public event SearchLyricsCompletedEventHandler SearchLyricsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://amp.fm/service/SearchTitle", RequestNamespace="http://amp.fm/service", ResponseNamespace="http://amp.fm/service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] SearchTitle(string searchPhrase, string[] additionalSearchParams) {
            object[] results = this.Invoke("SearchTitle", new object[] {
                        searchPhrase,
                        additionalSearchParams});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void SearchTitleAsync(string searchPhrase, string[] additionalSearchParams) {
            this.SearchTitleAsync(searchPhrase, additionalSearchParams, null);
        }
        
        /// <remarks/>
        public void SearchTitleAsync(string searchPhrase, string[] additionalSearchParams, object userState) {
            if ((this.SearchTitleOperationCompleted == null)) {
                this.SearchTitleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchTitleOperationCompleted);
            }
            this.InvokeAsync("SearchTitle", new object[] {
                        searchPhrase,
                        additionalSearchParams}, this.SearchTitleOperationCompleted, userState);
        }
        
        private void OnSearchTitleOperationCompleted(object arg) {
            if ((this.SearchTitleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchTitleCompleted(this, new SearchTitleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://amp.fm/service/SearchArtist", RequestNamespace="http://amp.fm/service", ResponseNamespace="http://amp.fm/service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] SearchArtist(string artistName) {
            object[] results = this.Invoke("SearchArtist", new object[] {
                        artistName});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void SearchArtistAsync(string artistName) {
            this.SearchArtistAsync(artistName, null);
        }
        
        /// <remarks/>
        public void SearchArtistAsync(string artistName, object userState) {
            if ((this.SearchArtistOperationCompleted == null)) {
                this.SearchArtistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchArtistOperationCompleted);
            }
            this.InvokeAsync("SearchArtist", new object[] {
                        artistName}, this.SearchArtistOperationCompleted, userState);
        }
        
        private void OnSearchArtistOperationCompleted(object arg) {
            if ((this.SearchArtistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchArtistCompleted(this, new SearchArtistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://amp.fm/service/SearchGenre", RequestNamespace="http://amp.fm/service", ResponseNamespace="http://amp.fm/service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] SearchGenre(string genre) {
            object[] results = this.Invoke("SearchGenre", new object[] {
                        genre});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void SearchGenreAsync(string genre) {
            this.SearchGenreAsync(genre, null);
        }
        
        /// <remarks/>
        public void SearchGenreAsync(string genre, object userState) {
            if ((this.SearchGenreOperationCompleted == null)) {
                this.SearchGenreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchGenreOperationCompleted);
            }
            this.InvokeAsync("SearchGenre", new object[] {
                        genre}, this.SearchGenreOperationCompleted, userState);
        }
        
        private void OnSearchGenreOperationCompleted(object arg) {
            if ((this.SearchGenreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchGenreCompleted(this, new SearchGenreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://amp.fm/service/SearchLyrics", RequestNamespace="http://amp.fm/service", ResponseNamespace="http://amp.fm/service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] SearchLyrics(string searchPhrase) {
            object[] results = this.Invoke("SearchLyrics", new object[] {
                        searchPhrase});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void SearchLyricsAsync(string searchPhrase) {
            this.SearchLyricsAsync(searchPhrase, null);
        }
        
        /// <remarks/>
        public void SearchLyricsAsync(string searchPhrase, object userState) {
            if ((this.SearchLyricsOperationCompleted == null)) {
                this.SearchLyricsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchLyricsOperationCompleted);
            }
            this.InvokeAsync("SearchLyrics", new object[] {
                        searchPhrase}, this.SearchLyricsOperationCompleted, userState);
        }
        
        private void OnSearchLyricsOperationCompleted(object arg) {
            if ((this.SearchLyricsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchLyricsCompleted(this, new SearchLyricsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1318")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValueType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1318")]
    public delegate void SearchTitleCompletedEventHandler(object sender, SearchTitleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1318")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchTitleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchTitleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1318")]
    public delegate void SearchArtistCompletedEventHandler(object sender, SearchArtistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1318")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchArtistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchArtistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1318")]
    public delegate void SearchGenreCompletedEventHandler(object sender, SearchGenreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1318")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchGenreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchGenreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1318")]
    public delegate void SearchLyricsCompletedEventHandler(object sender, SearchLyricsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1318")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchLyricsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchLyricsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591
