//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvp.Xml.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mvp.Xml.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or an empty string..
        /// </summary>
        internal static string ArgumentNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute axis can only be used as the last value in the path expresison. Invalid expression: {0}..
        /// </summary>
        internal static string AttributeAxisInvalid {
            get {
                return ResourceManager.GetString("AttributeAxisInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute match in expression cannot be specified when matching end elements..
        /// </summary>
        internal static string AttributeMatchCannotBeEndElement {
            get {
                return ResourceManager.GetString("AttributeMatchCannotBeEndElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix {0} could not be resolved with the provided namespace resolver..
        /// </summary>
        internal static string CannotResolvePrefix {
            get {
                return ResourceManager.GetString("CannotResolvePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mode specified..
        /// </summary>
        internal static string InvalidMode {
            get {
                return ResourceManager.GetString("InvalidMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name {0} is not a valid XML identifier..
        /// </summary>
        internal static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path {0} is invalid..
        /// </summary>
        internal static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path {0} is invalid. It must begin with one or two forward slashes (&quot;/&quot;)..
        /// </summary>
        internal static string InvalidPathStart {
            get {
                return ResourceManager.GetString("InvalidPathStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix {0} is not a valid XML identifier..
        /// </summary>
        internal static string InvalidPrefix {
            get {
                return ResourceManager.GetString("InvalidPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching expression or list is empty..
        /// </summary>
        internal static string MatchListEmpty {
            get {
                return ResourceManager.GetString("MatchListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace resolver is required..
        /// </summary>
        internal static string NamespaceResolverRequired {
            get {
                return ResourceManager.GetString("NamespaceResolverRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor has not been initialized yet..
        /// </summary>
        internal static string ProcessorNotInitialized {
            get {
                return ResourceManager.GetString("ProcessorNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root match cannot be an attribute match..
        /// </summary>
        internal static string RootMatchCantBeAttribute {
            get {
                return ResourceManager.GetString("RootMatchCantBeAttribute", resourceCulture);
            }
        }
    }
}
